apiVersion: apps/v1
kind: Deployment
metadata:
  name: rust-webapi
spec:
  replicas: 3
  template:
    spec:
      containers:
      - name: rust-webapi
        resources:
          limits:
            cpu: "1000m"
            memory: "1Gi"
          requests:
            cpu: "500m"
            memory: "512Mi"
