apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - configmap.yaml
  - secret.yaml
  - postgres-deployment.yaml
  - postgres-service.yaml
  - postgres-pvc.yaml
  - gateway.yaml
  - httproute.yaml
  - hpa.yaml
  - pdb.yaml
  - network-policy.yaml
  - postgres-network-policy.yaml

namespace: api

commonLabels:
  app.kubernetes.io/part-of: rust-webapi
  app.kubernetes.io/managed-by: kustomize
