apiVersion: apps/v1
kind: Deployment
metadata:
  name: rust-webapi
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: rust-webapi
        resources:
          limits:
            cpu: "300m"
            memory: "256Mi"
          requests:
            cpu: "100m"
            memory: "128Mi"
